# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on: push

name: check-deploy

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: R CMD check ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'oldrel-1'}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    timeout-minutes: 30
    steps:
      - uses: hugheylab/actions/R-CMD-check@main


  drat-deployment:
    needs: R-CMD-check
    runs-on: ubuntu-latest
    if: ${{ endswith(github.ref, '/master') || endswith(github.ref, '/main') }}
    env:
      GITHUB_PAT: ${{ secrets.JAKEJH_PAT }}
    timeout-minutes: 30
    steps:
      - uses: hugheylab/actions/drat-deployment@main
        with:
          personal-token: ${{ secrets.JAKEJH_PAT }}
